### PR TITLE
Patch header sync (WIP).

### PR DESCRIPTION
**Pull request by evoskuil**

### CODE REVIEW

**Comment by evoskuil** [comment]
Always pull everywhere.

**Comment by JasonCoombs** [comment]
it's a simple change, and I want to understand the reason for everything. my question was are you sure this builds based on what is now checked in, or do you have something else that might not be checked in yet?

**Comment by JasonCoombs** [comment]
this means the build succeeded, right?

https://travis-ci.org/libbitcoin/libbitcoin-node/builds/450367765

**Comment by evoskuil** [comment]
Yes, as does this: https://travis-ci.org/libbitcoin/libbitcoin-node/builds/450372227

**Pull request merged**
