### PR TITLE
Fix not_found error on start with empty block database.

### PR DESCRIPTION
**Pull request by evoskuil**

### CODE REVIEW

**Comment by evoskuil** [comment]
See: https://github.com/libbitcoin/libbitcoin-node/issues/64 and https://github.com/libbitcoin/libbitcoin-server/issues/129

**Comment by thecodefactory** [comment]
Possibly something environmental, but no blocks appear to get downloaded with this fix applied

```
20:17:18.889531 INFO [session] Starting with empty blockchain.
Server started, press CTRL-C to stop.
20:17:19.151163 INFO [protocol] Connected to peer [108.48.65.15:8333] (1 total)
20:17:54.117105 INFO [protocol] Connected to peer [62.238.34.125:8333] (2 total)
20:18:03.143781 INFO [protocol] Connected to peer [54.84.140.189:8333] (3 total)
20:18:07.741761 INFO [protocol] Connected to peer [78.145.35.77:8333] (4 total)
20:18:34.531361 INFO [protocol] Connected to peer [158.69.52.75:8333] (5 total)
20:18:34.662872 ERROR [protocol] Failure receiving verack from [158.69.52.75:8333] channel is stopped
20:18:48.320840 INFO [protocol] Connected to peer [50.31.149.59:8333] (5 total)
20:18:48.465392 ERROR [protocol] Failure receiving verack from [50.31.149.59:8333] channel is stopped
20:18:52.409343 INFO [protocol] Connected to peer [173.52.43.219:8333] (5 total)
20:18:52.549796 ERROR [protocol] Failure receiving verack from [173.52.43.219:8333] channel is stopped
20:18:58.275067 INFO [protocol] Connected to peer [72.182.112.200:8333] (5 total)
20:18:58.570283 INFO [protocol] Connected to peer [198.23.133.27:8333] (6 total)
20:19:40.983142 INFO [protocol] Connected to peer [174.50.237.113:8333] (7 total)
20:20:07.578291 INFO [protocol] Connected to peer [94.23.62.220:18333] (8 total)
20:22:19.151633 ERROR [session] Failure in channel revival: connection timed out
20:22:54.117448 ERROR [session] Failure in channel revival: connection timed out
20:23:03.144221 ERROR [session] Failure in channel revival: connection timed out
20:23:07.742045 ERROR [session] Failure in channel revival: connection timed out
20:23:58.275565 ERROR [session] Failure in channel revival: connection timed out
20:23:58.570633 ERROR [session] Failure in channel revival: connection timed out
20:24:40.983433 ERROR [session] Failure in channel revival: connection timed out
20:25:07.578712 ERROR [session] Failure in channel revival: connection timed out
^CPlease wait while server is stopping (code: 2)...
```

**Comment by evoskuil** [comment]
Ugh, I didn't take it all the way to syncing a block when I ran it.
```
20:53:34.866805 DEBUG [network] Receive inv [54.72.241.32:8333] (37 bytes)
20:53:35.642849 DEBUG [network] Receive inv [54.72.241.32:8333] (37 bytes)
20:53:38.105990 DEBUG [network] Receive inv [54.72.241.32:8333] (37 bytes)
20:53:38.105990 DEBUG [session] Block inventory from [54.72.241.32:8333] 00000000000000000983c3e66e5db2d5d1b45f33fb153adf8d6abdeb4bc94ae3
20:53:38.105990 DEBUG [network] Send getdata [54.72.241.32:8333] (61 bytes)
20:53:38.332003 DEBUG [network] Receive block [54.72.241.32:8333] (923005 bytes)
20:53:38.858033 DEBUG [protocol] Failure connecting [[2003:7a:f49:81c8:5853:bdbb:a60:7b1]:8333] connection timed out
20:53:38.858033 DEBUG [protocol] Connecting to peer [173.71.79.49:8333]
20:53:38.858033 DEBUG [network] caller(5)
20:53:38.858033 DEBUG [network] deadline(23)
20:53:39.642078 DEBUG [network] Receive inv [54.72.241.32:8333] (145 bytes)
20:53:39.651078 DEBUG [blockchain] Orphan pool add (1)
20:53:39.651078 DEBUG [poller] Potential block [00000000000000000983c3e66e5db2d5d1b45f33fb153adf8d6abdeb4bc94ae3]
20:53:39.652078 DEBUG [poller] Failed to fetch block locator: object does not exist
```
There is a follow-on issue with producing the block locator from an empty chain.

**Comment by evoskuil** [comment]
Turns out you can't get it from the network :/.

**Pull request merged**
